name: windows

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - '.readthedocs.yaml'
    tags:
      - V**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win64_mingw
          version: '6.5.3'
          aqtversion: ==3.1.7

      - name: Install cmake
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install cmake --no-progress

      - name: Install innosetup
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install innosetup --no-progress

      - name: Build all
        run: |
          git fetch --tags --force
          ./tools/sed/sed.exe -i 's/--long --dirty/--long/g' ./tools/generate_info.ps1
          ./tools/sed/sed.exe -i "s/QT_DIR=C:\/Qt\/Qt6.2.0\/6.2.0\/mingw81_32\/bin/QT_DIR=%Qt5_Dir%/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/QT_TOOLS_DIR=C:\/Qt\/Qt6.2.0\/Tools\/mingw810_32\/bin/QT_TOOLS_DIR=C:\/ProgramData\/Chocolatey\/lib\/mingw\/tools\/install\/mingw64\/bin/g" ./build_setup.bat
          c:/Windows/system32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy Bypass -NoLogo -NoProfile -File "./tools/generate_info.ps1" > ./build_info.inc
          ./build_setup.bat

      - name: Upload build asserts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: QFSViewer_windows
          path: |
            ./output/*.exe

      - name: Run tests
        run: |
          ./InnoSetup/build/QFSViewer.exe --version
