name: windows

on:
  push:
    branches: [ main, add_lwext4 ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.2.1
        with:
          arch: win64_mingw81
          version: '6.2.0'

      - name: Install prerequisites
        run: |
          Choco-Install -PackageName innosetup --force
          Choco-Install -PackageName cmake --force

      - uses: msys2/setup-msys2@v2

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --abbrev=10 --tags | ./tools/awk/awk.exe '{print \"\\\"\"$0\"\\\"\"}'  > git_tag.inc
          ./tools/sed/sed.exe -i "s/git_tag.inc/git_tag.ci.inc/g" QFSViewer.pro
          ./tools/sed/sed.exe -i "s/QT_DIR=C:\/Qt\/Qt6.2.0\/6.2.0\/mingw81_32\/bin/QT_DIR=%Qt5_Dir%/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/QT_TOOLS_DIR=C:\/Qt\/Qt6.2.0\/Tools\/mingw810_32\/bin/QT_TOOLS_DIR=C:\/ProgramData\/Chocolatey\/lib\/mingw\/tools\/install\/mingw64\/bin/g" ./build_setup.bat
          ./build_setup.bat

      - name: Upload build asserts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: QFSViewer_windows
          path: |
            ./InnoSetup/QFSViewer_setup.exe

      - name: Run tests
        run: |
          ./InnoSetup/build/QFSViewer.exe --version